### ISSUE TITLE
CronJobs are throwing an error

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-monorepo#1215]
### Discussed in https://github.com/MetaMask/snaps-monorepo/discussions/1206

<div type='discussions-op-text'>

<sup>Originally posted by **saicharan0124** February 18, 2023</sup>
 im gettting this error **"(0 , i.isCronjobSpecificationArray) is not a function"** what should i do to clear it ?</div>

**Comment by FrederikBolding** [comment]
This was fixed in https://github.com/MetaMask/snaps-monorepo/pull/1134 but remains a problem in the current release as this PR was not included in that release. 

This will be automatically solved in the following release of MetaMask Flask. Users can work around this by building MetaMask Flask locally.

We should prioritize landing the E2E for cronjobs to prevent this from happening again.
