### ISSUE TITLE
Identify and constrain timers

### ISSUE THREAD

**Issue by kumavis** [MetaMask/snaps-monorepo#211]
Related: MetaMask/metamask-snaps-beta#135 

`Date` and other platform APIs can provide subtle timers. We should make a decent effort to constrain them, and then process-separate as possible.

**Comment by rekmarks** [comment]
We

**Comment by rekmarks** [comment]
We already constrain `setTimeout` and `setInterval` in the iframe execution environment, but we have not looked into e.g. `Date`.

**Comment by kenhkan** [comment]
A note from refinement session: We need to constrain `Date` as well.

**Comment by ritave** [comment]
With help of @naugtur we've identified:
1. `Date()`
2. `new Date()`
3. `Date.now()`
4. `window.performance`
5. [`DOMHighResTimeStamp`](https://developer.mozilla.org/en-US/docs/Web/API/DOMHighResTimeStamp)
6. `process.hrtime()`
7. `setTimeout` and `setInterval` if they are not constrained by the browser / the load is low.
   1. They are not constrained by the browser in general case, [only when nested](https://html.spec.whatwg.org/multipage/timers-and-user-prompts.html#timers).
8. [`alarms`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms)
9. [TC39 Temporal](https://tc39.es/proposal-temporal/docs/index.html)

**Comment by naugtur** [comment]
Note that the paper goes very deep into searching for time and some of it may not be practical. Like things that take predictable time synchronously - that's not useful for timing attacks because nothing can be done while the time is being measured.

As for random noise adding when rounding, the rounding function would need one item of state to ensure the time doesn't fluctuate back and forth, because it could be used to defeat the rounding. 
The state doesn't need to be preserved across shutdowns or anything, just be there as the time measurements keep being called by a snap.
```js
function createRounder({ factor }) {
  let current = 0;
  return (time) => {
    const newRounded = Math.round( (time/factor) + tinyRandomNoise );
    if(newRounded>current){
      current = newRounded;
    }
    return current;
}

**Comment by FrederikBolding** [comment]
I might be missing something but would it be simpler to just add a bit of noise instead of rounding at all?

e.g.
```
  const getNoise = () =>crypto.getRandomValues(new Uint32Array(1))[0] % 5;

  let currentTime = 0;
  const now = () => {
    const actual = Date.now();
    const new = actual + getNoise();
    if (new > currentTime) {
      currentTime = new;
    }
    return currentTime;
  };
```

**Comment by FrederikBolding** [comment]
Also, in this thread we have been mainly discussing `Date` so far. Do we need to add some noise to reduce precision on `setTimeout` and `setInterval` as well?

**Comment by GuillaumeRx** [comment]
> Also, in this thread we have been mainly discussing `Date` so far. Do we need to add some noise to reduce precision on `setTimeout` and `setInterval` as well? We have them constrained to not overlap handles between snaps right now, but they still have normal precision.

Yes, that was part of the work but likely more easier than adding the fuzziness in `Date`.

**Comment by naugtur** [comment]
@FrederikBolding 
Rounding removes more information about the values and removes the precision so the developer would not believe they're getting precise values. With more of the information gone, Math.random might suffice to generate the noise and is cheaper. But overall I agree your proposal seems fine and is clearly better than just rounding.

As for setTimeout and setInterval - they have some noise built into them by nature (they run on the next event loop pass after the time for which they were scheduled). I'm not sure if there's a benefit to disturbing them. I would forbid using a timeout value of zero for good measure. We don't want that kind of behavior. Especially for setInterval. 
We might want setInterval to throw if less than 10 is passed in as timeout.  
Not sure what to do with setTimeout, because it's sometimes used to make something happen right away but asynchronously, so throwing would break the ecosystem potentially. Silent Math.max(10, timeout) is also debatable, but would not break any non-silly code.

**Comment by FrederikBolding** [comment]
@naugtur 

I think throwing on `setInterval` or `setTimeout` depending on passed args could both be ecosystem breakers. I would much rather set a slightly higher minimum that we automatically enforce (e.g. `Math.max(10, timeout)`). Do we think a minimum of 10ms is fine?

If we don't do any rounding what should be the maximum value for noise? Also 10ms? 5? something else? In general it seems simpler to me to just add some random noise, but persist it, instead of rounding.

**Comment by FrederikBolding** [comment]
Potential WIP solution: https://github.com/MetaMask/snaps-monorepo/pull/1118
