### ISSUE TITLE
Add environment variable support to snaps cli build

### ISSUE THREAD

**Issue by onetrickwolf** [MetaMask/snaps-monorepo#679]
Could be useful to either pipe in a dotenv file automatically or pass environmental variables for `mm-snap`. 

I know currently you could use webpack or rollup or any bundle/prebuild step but it would be much simpler to be able to just include a dotenv or some env arguments in the command line.

Not super familiar with how the snaps build currently works, but I see [it's using browserify arguments](https://github.com/MetaMask/snaps-skunkworks/blob/main/packages/cli/src/cmds/build/bundle.ts#L30) already might be able to use something like this for inspiration: https://github.com/hughsk/envify

Or possibly at the babel plugins: https://babeljs.io/docs/en/babel-plugin-transform-inline-environment-variables

https://www.npmjs.com/package/babel-plugin-inline-dotenv

**Comment by ritave** [comment]
Hey @onetrickwolf. We allow you to extend the internal browserify with any plugins you want [using the config file](https://github.com/MetaMask/snaps-skunkworks/tree/main/packages/cli#configuration-file).

Since env variables being replaced during compile time instead of loaded during run-time, envify behaviour would be non-obvious to end-users. Do you still think we should support it?

**Comment by Montoya** [comment]
Closing this issue and will update our documentation to include a link to your example project.
